[tool.black]
line-length = 88
target-version = ["py37"]
include = """
(
    ^/Lib/fontTools/pens
    | ^/Lib/fontTools/cu2qu/ufo.py
    | ^/Lib/fontTools/ufoLib/glifLib.py
    | ^/Lib/fontTools/varLib/interpolatable.py
)
"""
