#! /usr/bin/env python3
"""Declare the attributes that sstruct unpacks onto table objects.

Table classes get most of their attributes from ``sstruct.unpack(fmt, data,
self)``, which assigns them by name at runtime. Nothing declares them, so no
type checker or IDE can see them. This writes a declaration block for each
such class, between BEGIN/END markers, and rewrites only what is inside.

Only formats that unpack into ``self`` are used: a module-level format string
may equally describe a nested record that never lands on the table object.

Where the attribute ends up holding something other than the wire type -- the
decompile step may replace it -- annotate the field in the format string:

    minLeftSideBearing:  h    # py:float
    axisTag:             4s   # py:"Tag | None"

sstruct already discards a trailing comment, so the hint costs it nothing.

Usage:
    PYTHONPATH=Lib python MetaTools/buildTableStubs.py [--check]
"""

import argparse
import ast
import importlib
import pkgutil
import re
import sys
from pathlib import Path
from types import ModuleType

from fontTools.misc import sstruct
from fontTools.ttLib import tables

BEGIN = "    # BEGIN sstruct decode -- generated by MetaTools/buildTableStubs.py"
END = "    # END sstruct decode"

STRUCT_TO_PY = {
    **dict.fromkeys("bBhHiIlLqQ", "int"),
    **dict.fromkeys("fd", "float"),
    **dict.fromkeys("spc", "str"),
    "?": "bool",
}

_HINT = re.compile(
    r"""\bpy:\s*(?: " (?P<dq>[^"]*) " | ' (?P<sq>[^']*) ' | (?P<bare>[^\s#]+) )""",
    re.VERBOSE,
)
_FIELD = re.compile(r"\s*([A-Za-z_]\w*)\s*:\s*[^#\s]+\s*(?:#(?P<comment>.*))?$")

TABLES_DIR = (
    Path(__file__).resolve().parent.parent / "Lib" / "fontTools" / "ttLib" / "tables"
)


def type_hints(fmt: str) -> dict[str, str]:
    """
    Read per-field ``# py:`` overrides out of an sstruct format string.

    Args:
        fmt (str): An sstruct format string.

    Returns:
        dict[str, str]: Field name to the python type spelled in its comment.
    """
    hints: dict[str, str] = {}
    for line in re.split("[\n;]", fmt):
        m = _FIELD.match(line)
        if m and m.group("comment"):
            h = _HINT.search(m.group("comment"))
            if h:
                hints[m.group(1)] = (h["dq"] or h["sq"] or h["bare"]).strip()
    return hints


def field_types(fmt: str) -> dict[str, str]:
    """
    Map an sstruct format string to it's python type

    Args:
        fmt (str): An sstruct format string.

    Returns:
        dict[str, str]: Field -> type
    """
    _, names, fixes = sstruct.getformat(fmt)
    out: dict[str, str] = {
        n: "float" if n in fixes else STRUCT_TO_PY.get(c.lstrip("0123456789"), "Any")
        for n, c in names.items()
    }
    out.update({k: v for k, v in type_hints(fmt).items() if k in out})
    return out


def _self_format(call: ast.Call) -> str | None:
    """Return the format-constant name if this sstruct call targets ``self``."""
    fn = call.func
    if not isinstance(fn, ast.Attribute) or not isinstance(fn.value, ast.Name):
        return None
    if fn.value.id != "sstruct":
        return None
    idx = {"unpack": 2, "unpack2": 2, "pack": 1}.get(fn.attr)
    if idx is None or len(call.args) <= idx:
        return None
    obj, fmt = call.args[idx], call.args[0]
    if isinstance(obj, ast.Name) and obj.id == "self" and isinstance(fmt, ast.Name):
        return fmt.id
    return None


def strip_blocks(text: str) -> str:
    """Remove previously generated blocks so the pass is idempotent."""
    lines = text.splitlines()
    out: list[str] = []
    i = 0
    while i < len(lines):
        if not lines[i].startswith(BEGIN):
            out.append(lines[i])
            i += 1
            continue
        if out and not out[-1].strip():
            out.pop()
        while i < len(lines) and not lines[i].startswith(END):
            i += 1
        i += 1
    return "\n".join(out) + "\n"


def declared(cls: ast.ClassDef) -> set[str]:
    """Names the class already annotates by hand, which take precedence."""
    return {
        s.target.id
        for s in cls.body
        if isinstance(s, ast.AnnAssign) and isinstance(s.target, ast.Name)
    }


def insertion_line(cls: ast.ClassDef) -> int:
    """Find the insertion point"""
    at = cls.lineno
    for i, stmt in enumerate(cls.body):
        is_doc = (
            i == 0
            and isinstance(stmt, ast.Expr)
            and isinstance(stmt.value, ast.Constant)
            and isinstance(stmt.value.value, str)
        )
        if not (is_doc or isinstance(stmt, (ast.AnnAssign, ast.Assign))):
            break
        at = stmt.end_lineno or at
    return at


def declared_format(cls: ast.ClassDef, mod: ModuleType) -> list[str]:
    """Formats a class claims via a ``binaryFormat`` attribute."""
    for s in cls.body:
        if not (
            isinstance(s, ast.Assign)
            and any(
                isinstance(t, ast.Name) and t.id == "binaryFormat" for t in s.targets
            )
        ):
            continue
        names = s.value.elts if isinstance(s.value, ast.Tuple) else [s.value]
        out = []
        for n in names:
            fmt = getattr(mod, n.id, None) if isinstance(n, ast.Name) else None
            if isinstance(fmt, str):
                out.append(fmt)
        return out
    return []


def rewrite(module: str) -> tuple[str, str] | None:
    """Return (path, new source) for a module that needs a block, else None."""
    mod = importlib.import_module(f"fontTools.ttLib.tables.{module}")
    path = TABLES_DIR / f"{module}.py"
    text = strip_blocks(path.read_text(encoding="utf-8"))
    tree = ast.parse(text)

    inserts: dict[int, dict[str, str]] = {}
    for cls in (n for n in ast.walk(tree) if isinstance(n, ast.ClassDef)):
        fields: dict[str, str] = {}
        # check for "binaryformat=..."
        for fmt in declared_format(cls, mod):
            fields.update(field_types(fmt))
        for call in (n for n in ast.walk(cls) if isinstance(n, ast.Call)):
            const = _self_format(call)
            fmt = getattr(mod, const, None) if const else None
            if isinstance(fmt, str):
                fields.update(field_types(fmt))
        fields = {n: t for n, t in fields.items() if n not in declared(cls)}
        if fields:
            inserts[insertion_line(cls)] = fields

    if not inserts:
        return None
    lines = text.splitlines()
    for at in sorted(inserts, reverse=True):
        # Pad only where there is not already a blank line
        lead = [] if at and not lines[at - 1].strip() else [""]
        tail = [""] if at < len(lines) and lines[at].strip() else []
        block = lead + [BEGIN]
        block += [f"    {n}: {t}" for n, t in sorted(inserts[at].items())]
        block += [END] + tail
        lines[at:at] = block
    return str(path), "\n".join(lines) + "\n"


def build(check: bool) -> int:
    """Write (or verify) the generated blocks. Returns a process exit code."""
    stale = written = 0
    for _, module, _ in pkgutil.iter_modules(tables.__path__):
        try:
            result = rewrite(module)
        except Exception as exc:  # a table module that will not import
            print(f"  skipped {module}: {exc}")
            continue
        if result is None:
            continue
        path, new = result
        if Path(path).read_text(encoding="utf-8") == new:
            continue
        if check:
            print(f"  stale: {path}")
            stale += 1
        else:
            Path(path).write_text(new, encoding="utf-8")
            written += 1
    if check:
        if stale:
            print(f"{stale} file(s) out of date")
            return 1
        print("All generated blocks are up to date.")
        return 0
    print(f"Wrote sstruct declarations into {written} module(s).")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--check", action="store_true", help="report drift instead of writing"
    )
    args = ap.parse_args()
    return build(args.check)


if __name__ == "__main__":
    sys.exit(main())
