# DON'T EDIT! This file is generated by MetaTools/buildTableList.py.
def _moduleFinderHint():
	"""Dummy function to let modulefinder know what tables may be
	dynamically imported. Generated by MetaTools/buildTableList.py.
	"""
	from fontTools.ttLib.tables import B_A_S_E_
	from fontTools.ttLib.tables import C_B_D_T_
	from fontTools.ttLib.tables import C_B_L_C_
	from fontTools.ttLib.tables import C_F_F_
	from fontTools.ttLib.tables import C_O_L_R_
	from fontTools.ttLib.tables import C_P_A_L_
	from fontTools.ttLib.tables import D_S_I_G_
	from fontTools.ttLib.tables import E_B_D_T_
	from fontTools.ttLib.tables import E_B_L_C_
	from fontTools.ttLib.tables import G_D_E_F_
	from fontTools.ttLib.tables import G_M_A_P_
	from fontTools.ttLib.tables import G_P_K_G_
	from fontTools.ttLib.tables import G_P_O_S_
	from fontTools.ttLib.tables import G_S_U_B_
	from fontTools.ttLib.tables import J_S_T_F_
	from fontTools.ttLib.tables import L_T_S_H_
	from fontTools.ttLib.tables import M_E_T_A_
	from fontTools.ttLib.tables import O_S_2f_2
	from fontTools.ttLib.tables import S_I_N_G_
	from fontTools.ttLib.tables import S_V_G_
	from fontTools.ttLib.tables import T_S_I_B_
	from fontTools.ttLib.tables import T_S_I_D_
	from fontTools.ttLib.tables import T_S_I_J_
	from fontTools.ttLib.tables import T_S_I_P_
	from fontTools.ttLib.tables import T_S_I_S_
	from fontTools.ttLib.tables import T_S_I_V_
	from fontTools.ttLib.tables import T_S_I__0
	from fontTools.ttLib.tables import T_S_I__1
	from fontTools.ttLib.tables import T_S_I__2
	from fontTools.ttLib.tables import T_S_I__3
	from fontTools.ttLib.tables import T_S_I__5
	from fontTools.ttLib.tables import V_O_R_G_
	from fontTools.ttLib.tables import _c_m_a_p
	from fontTools.ttLib.tables import _c_v_t
	from fontTools.ttLib.tables import _f_p_g_m
	from fontTools.ttLib.tables import _g_a_s_p
	from fontTools.ttLib.tables import _g_l_y_f
	from fontTools.ttLib.tables import _h_d_m_x
	from fontTools.ttLib.tables import _h_e_a_d
	from fontTools.ttLib.tables import _h_h_e_a
	from fontTools.ttLib.tables import _h_m_t_x
	from fontTools.ttLib.tables import _k_e_r_n
	from fontTools.ttLib.tables import _l_o_c_a
	from fontTools.ttLib.tables import _m_a_x_p
	from fontTools.ttLib.tables import _n_a_m_e
	from fontTools.ttLib.tables import _p_o_s_t
	from fontTools.ttLib.tables import _p_r_e_p
	from fontTools.ttLib.tables import _v_h_e_a
	from fontTools.ttLib.tables import _v_m_t_x
