# DON'T EDIT! This file is generated by MetaTools/buildTableList.py.
def _moduleFinderHint():
	"""Dummy function to let modulefinder know what tables may be
	dynamically imported. Generated by MetaTools/buildTableList.py.
	"""
	from . import B_A_S_E_
	from . import C_B_D_T_
	from . import C_B_L_C_
	from . import C_F_F_
	from . import C_O_L_R_
	from . import C_P_A_L_
	from . import D_S_I_G_
	from . import E_B_D_T_
	from . import E_B_L_C_
	from . import F_F_T_M_
	from . import G_D_E_F_
	from . import G_M_A_P_
	from . import G_P_K_G_
	from . import G_P_O_S_
	from . import G_S_U_B_
	from . import J_S_T_F_
	from . import L_T_S_H_
	from . import M_E_T_A_
	from . import O_S_2f_2
	from . import S_I_N_G_
	from . import S_V_G_
	from . import T_S_I_B_
	from . import T_S_I_D_
	from . import T_S_I_J_
	from . import T_S_I_P_
	from . import T_S_I_S_
	from . import T_S_I_V_
	from . import T_S_I__0
	from . import T_S_I__1
	from . import T_S_I__2
	from . import T_S_I__3
	from . import T_S_I__5
	from . import V_O_R_G_
	from . import _c_m_a_p
	from . import _c_v_t
	from . import _f_p_g_m
	from . import _g_a_s_p
	from . import _g_l_y_f
	from . import _h_d_m_x
	from . import _h_e_a_d
	from . import _h_h_e_a
	from . import _h_m_t_x
	from . import _k_e_r_n
	from . import _l_o_c_a
	from . import _m_a_x_p
	from . import _n_a_m_e
	from . import _p_o_s_t
	from . import _p_r_e_p
	from . import _s_b_i_x
	from . import _v_h_e_a
	from . import _v_m_t_x
