#! /usr/bin/env python

from __future__ import division
import sys
import os
import tempfile
import subprocess
from fontTools import analysis

testSuite = ['FreeMono-call-endf.ttx', 'FreeMono-empty-fdef.ttx', 'FreeMono-gfv.ttx', 'FreeMono-inf-loop.ttx', 
             'FreeMono-jmpr.ttx', 'FreeMono-jrot.ttx', 'FreeMono-jrot-jrof.ttx',
             'FreeMono-max.ttx', 'FreeMono-max-no-simplify.ttx',
             'FreeMono-pop.ttx', 'FreeMono-simple-loop.ttx', 'FreeMono-subset-A.ttx']

def main(args):
    scriptdir = os.path.dirname(os.path.realpath(__file__))
    stored_stdout = sys.stdout
    for fontFile in testSuite:
        print ("Testing "+fontFile)
        (fd, tmpnam) = tempfile.mkstemp()
        sys.stdout = os.fdopen(fd, 'w')

        analysis.main(['-ipf', os.path.join(scriptdir, "..", "TestData" , fontFile)])
        sys.stdout.close()
        sys.stdout = stored_stdout

        expectedFile = os.path.join(scriptdir, "..", "TestData" , fontFile + '.coi')
        rv = subprocess.call(['diff', '-u', expectedFile, tmpnam])
        if rv != 0:
            print "... error!"

        os.remove(tmpnam)

if __name__ == '__main__':
  main(sys.argv[1:])

